#!/usr/bin/env node

// When using the git repository as a project dependency, `npm install` tries to
// add the generated cli file from `./lib/bin/cli.js` before it has been
// generated by the `postinstall` script. This is a workaround for that issue.
//
// For more information, see: https://github.com/tgriesser/knex/issues/1180
//
exports = require('knex/lib/bin/cli');
